# Generated by Django 2.0.2 on 2018-03-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name="Character's name")),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=False)),
                ('rage', models.IntegerField(default=300)),
                ('strength', models.IntegerField(default=5)),
                ('inventory', models.ManyToManyField(to='armory.Item', verbose_name='Items the character has')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cleric',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name="Character's name")),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=False)),
                ('using_shield', models.BooleanField(default=False)),
                ('mana', models.IntegerField(default=100)),
                ('inventory', models.ManyToManyField(to='armory.Item', verbose_name='Items the character has')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name="Character's name")),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=False)),
                ('using_shield', models.BooleanField(default=False)),
                ('rage', models.IntegerField(default=100)),
                ('inventory', models.ManyToManyField(to='armory.Item', verbose_name='Items the character has')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mage',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name="Character's name")),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=True)),
                ('mana', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thief',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name="Character's name")),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=False)),
                ('is_sneaking', models.BooleanField(default=False)),
                ('energy', models.IntegerField(default=100)),
                ('inventory', models.ManyToManyField(to='armory.Item', verbose_name='Items the character has')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zombie',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name="Character's name")),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=False)),
                ('rage', models.IntegerField(default=100)),
                ('hp', models.IntegerField(default=50)),
                ('inventory', models.ManyToManyField(to='armory.Item', verbose_name='Items the character has')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Necromancer',
            fields=[
                ('mage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charactercreator.Mage')),
                ('talisman_charged', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('charactercreator.mage',),
        ),
        migrations.AddField(
            model_name='mage',
            name='inventory',
            field=models.ManyToManyField(to='armory.Item', verbose_name='Items the character has'),
        ),
    ]
