# Generated by Django 2.0.2 on 2018-03-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleric',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=False)),
                ('rage', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=0)),
                ('using_shield', models.BooleanField(default=False)),
                ('mana', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=False)),
                ('using_shield', models.BooleanField(default=False)),
                ('rage', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mage',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=True)),
                ('mana', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thief',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('wisdom', models.IntegerField(default=1)),
                ('has_pet', models.BooleanField(default=False)),
                ('rage', models.IntegerField(default=0)),
                ('mana', models.IntegerField(default=0)),
                ('is_sneaking', models.BooleanField(default=False)),
                ('energy', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Necromancer',
            fields=[
                ('mage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charactercreator.Mage')),
                ('talisman_charged', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('charactercreator.mage',),
        ),
    ]
