# Generated by Django 2.0.2 on 2018-03-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charactercreator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleric',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='cleric',
            name='rage',
        ),
        migrations.RemoveField(
            model_name='thief',
            name='mana',
        ),
        migrations.RemoveField(
            model_name='thief',
            name='rage',
        ),
    ]
