# Generated by Django 2.0.2 on 2018-03-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactercreator', '0002_auto_20180308_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('thief_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charactercreator.Thief')),
                ('speed', models.IntegerField(default=100)),
            ],
            bases=('charactercreator.thief',),
        ),
    ]
