# Generated by Django 2.0.2 on 2018-03-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactercreator', '0002_auto_20180308_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(related_name='items', to='armory.Item', verbose_name='Items the character has'),
        ),
    ]
